# Generated by Django 4.2.4 on 2023-08-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Web service nomi, masalan: Telegram', max_length=255, verbose_name='Web service nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: IELTS 10 kun ichida', max_length=255, verbose_name='Manba nomi')),
                ('url', models.URLField(verbose_name='Manba linki')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar uchun")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Kategoriyaysi')),
                ('web_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.webservice', verbose_name='Web service nomi')),
            ],
        ),
    ]
